[package]
name = "game-dumper"
version = "1.0.0"
edition = "2021"
description = "SDK Dumper - Escanea el proceso del juego y autogenera la carpeta SDK con offsets"

[dependencies]
colored = "2.1"
chrono = "0.4"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = [
    "processthreadsapi",
    "memoryapi",
    "handleapi",
    "tlhelp32",
    "psapi",
    "winnt",
    "errhandlingapi",
    "libloaderapi",
    "wow64apiset",
    "sysinfoapi",
    "basetsd"
]}
