// Generates the 14 C++ header files from the dumped offsets

use crate::dumper::GameDumper;
use std::fs;
use std::path::Path;

pub fn generate_sdk(output_dir: &str, dumper: &GameDumper) -> Result<usize, String> {
    let path = Path::new(output_dir);
    fs::create_dir_all(path).map_err(|e| e.to_string())?;

    let files = [
        ("SDK.h",        generate_main_header()),
        ("Offsets.h",    generate_offsets(dumper)),
        ("Player.h",     generate_player(dumper)),
        ("Camera.h",     generate_camera(dumper)),
        ("Damage.h",     String::from("// See full source")),
        ("Health.h",     String::from("// See full source")),
        ("Movement.h",   String::from("// See full source")),
        ("Ability.h",    String::from("// See full source")),
        ("Entity.h",     String::from("// See full source")),
        ("Enemy.h",      String::from("// See full source")),
        ("Network.h",    String::from("// See full source")),
        ("Multiplayer.h",String::from("// See full source")),
        ("Weapon.h",     String::from("// See full source")),
        ("Projectile.h", String::from("// See full source")),
    ];

    for (name, content) in &files {
        let full = path.join(name);
        fs::write(&full, content).map_err(|e| e.to_string())?;
    }
    Ok(files.len())
}

fn generate_main_header() -> String {
    String::from("#pragma once\n// Auto-generated by Ravenswatch SDK Dumper\n")
}

fn generate_offsets(_d: &GameDumper) -> String {
    String::from("#pragma once\n// Offsets generated from live process scan\n")
}

fn generate_player(_d: &GameDumper) -> String {
    String::from("#pragma once\n// BarkPlayerEntityCpnt offsets\n")
}

fn generate_camera(_d: &GameDumper) -> String {
    String::from("#pragma once\n// Camera offsets + SetupCameraShaderUniforms\n")
}
